name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a multi-line script
      run: |
        echo ----------------------
        pwd
        sudo apt-get update -y
        sudo apt-get install -y php-cli
        php index.php
        echo ----------------------
